title:             Rajesh's Blog
email:             kr.rajesh.phy@gmail.com
description:       A collection of the articles I wrote about several of my Life Experiences, Creations, Travel Guides, and Projects.
author:            Rajesh Kumar
baseurl:           "/blog"
url:               "https://consultt.github.io"
logo:              "/img/logo.png"

# Social Profiles

github_username:    bittugithub1
facebook_username:  Rajesh-Physics-103463492361482
linkedin_username:  rajesh-kumar-muri
goodreads_username: 150767937-rajesh

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

jekyll-archives:
  enabled:
      - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

    #algolia:
    #application_id: JOKM4G43ZF
    #index_name:     Jekyll Search
    #search_only_api_key: 1729cd0904b1ff8a78cd7b9f5bfbe30f


